const express = require('express');
const router = express.Router();
const fs = require('fs');
const path = require('path');

const ENV_FILE_PATH = path.join(__dirname, '../.env');

// Helper function to read .env file
const readEnvFile = () => {
  try {
    if (!fs.existsSync(ENV_FILE_PATH)) {
      console.log('Creating new .env file');
      fs.writeFileSync(ENV_FILE_PATH, '');
    }

    const envContent = fs.readFileSync(ENV_FILE_PATH, 'utf8');
    const envVars = {};

    envContent.split('\n').forEach(line => {
      const trimmedLine = line.trim();
      if (trimmedLine && !trimmedLine.startsWith('#')) {
        const [key, ...valueParts] = trimmedLine.split('=');
        if (key && valueParts.length > 0) {
          envVars[key.trim()] = valueParts.join('=').trim();
        }
      }
    });

    return envVars;
  } catch (error) {
    console.error('Error reading .env file:', error);
    throw error;
  }
};

// Helper function to write .env file
const writeEnvFile = (envVars) => {
  try {
    const envLines = [];
    
    // Add header comment
    envLines.push('# CardCat Application Environment Variables');
    envLines.push('# Generated by Settings API');
    envLines.push('');

    // Add standard variables
    envLines.push('# Server Configuration');
    envLines.push(`PORT=${envVars.PORT || '3000'}`);
    envLines.push(`DATABASE_URL=${envVars.DATABASE_URL || 'mongodb://localhost/cardcat'}`);
    envLines.push(`JWT_SECRET=${envVars.JWT_SECRET || ''}`);
    envLines.push(`REFRESH_TOKEN_SECRET=${envVars.REFRESH_TOKEN_SECRET || ''}`);
    envLines.push('');

    // Add eBay API configuration
    envLines.push('# eBay API Configuration');
    envLines.push(`EBAY_APP_ID=${envVars.EBAY_APP_ID || ''}`);
    envLines.push(`EBAY_CERT_ID=${envVars.EBAY_CERT_ID || ''}`);
    envLines.push(`EBAY_DEV_ID=${envVars.EBAY_DEV_ID || ''}`);
    envLines.push('');

    // Add Ollama configuration
    envLines.push('# Ollama Configuration');
    envLines.push(`OLLAMA_URL=${envVars.OLLAMA_URL || 'http://localhost:11434'}`);
    envLines.push(`OLLAMA_MODEL=${envVars.OLLAMA_MODEL || 'llava'}`);

    const envContent = envLines.join('\n');
    fs.writeFileSync(ENV_FILE_PATH, envContent);

    console.log('Successfully updated .env file');
    return true;
  } catch (error) {
    console.error('Error writing .env file:', error);
    throw error;
  }
};

// GET /api/settings/ebay - Get eBay API configuration
router.get('/ebay', async (req, res) => {
  try {
    console.log('\n=== GET EBAY SETTINGS REQUEST ===');

    const envVars = readEnvFile();

    const ebayConfig = {
      appId: envVars.EBAY_APP_ID || '',
      certId: envVars.EBAY_CERT_ID || '',
      devId: envVars.EBAY_DEV_ID || '',
      configured: !!(envVars.EBAY_APP_ID && envVars.EBAY_CERT_ID && envVars.EBAY_DEV_ID)
    };

    console.log('eBay configuration loaded:', {
      appId: ebayConfig.appId ? '***configured***' : 'not set',
      certId: ebayConfig.certId ? '***configured***' : 'not set',
      devId: ebayConfig.devId ? '***configured***' : 'not set',
      configured: ebayConfig.configured
    });

    res.json(ebayConfig);

  } catch (error) {
    console.error('Error getting eBay settings:', error);
    res.status(500).json({
      error: 'Failed to get eBay settings',
      message: error.message
    });
  }
});

// POST /api/settings/ebay - Save eBay API configuration
router.post('/ebay', async (req, res) => {
  try {
    console.log('\n=== SAVE EBAY SETTINGS REQUEST ===');
    
    const { appId, certId, devId } = req.body;

    console.log('Received eBay settings:', {
      appId: appId ? '***provided***' : 'not provided',
      certId: certId ? '***provided***' : 'not provided',
      devId: devId ? '***provided***' : 'not provided'
    });

    if (!appId || !certId || !devId) {
      return res.status(400).json({
        error: 'All eBay API credentials are required',
        message: 'Please provide App ID, Certificate ID, and Developer ID'
      });
    }

    // Read current .env file
    const envVars = readEnvFile();

    // Update eBay settings
    envVars.EBAY_APP_ID = appId.trim();
    envVars.EBAY_CERT_ID = certId.trim();
    envVars.EBAY_DEV_ID = devId.trim();

    // Write updated .env file
    writeEnvFile(envVars);

    // Update process.env for immediate use
    process.env.EBAY_APP_ID = appId.trim();
    process.env.EBAY_CERT_ID = certId.trim();
    process.env.EBAY_DEV_ID = devId.trim();

    console.log('✅ eBay settings saved successfully');

    res.json({
      success: true,
      message: 'eBay API settings saved successfully',
      configured: true
    });

  } catch (error) {
    console.error('Error saving eBay settings:', error);
    res.status(500).json({
      error: 'Failed to save eBay settings',
      message: error.message
    });
  }
});

// GET /api/settings/ollama - Get Ollama configuration
router.get('/ollama', async (req, res) => {
  try {
    console.log('\n=== GET OLLAMA SETTINGS REQUEST ===');

    const envVars = readEnvFile();

    const ollamaConfig = {
      url: envVars.OLLAMA_URL || 'http://localhost:11434',
      model: envVars.OLLAMA_MODEL || 'llava',
      configured: !!(envVars.OLLAMA_URL && envVars.OLLAMA_MODEL)
    };

    console.log('Ollama configuration loaded:', ollamaConfig);

    res.json(ollamaConfig);

  } catch (error) {
    console.error('Error getting Ollama settings:', error);
    res.status(500).json({
      error: 'Failed to get Ollama settings',
      message: error.message
    });
  }
});

// POST /api/settings/ollama - Save Ollama configuration
router.post('/ollama', async (req, res) => {
  try {
    console.log('\n=== SAVE OLLAMA SETTINGS REQUEST ===');
    
    const { url, model } = req.body;

    console.log('Received Ollama settings:', { url, model });

    if (!url || !model) {
      return res.status(400).json({
        error: 'Ollama URL and model are required',
        message: 'Please provide both Ollama URL and model name'
      });
    }

    // Read current .env file
    const envVars = readEnvFile();

    // Update Ollama settings
    envVars.OLLAMA_URL = url.trim();
    envVars.OLLAMA_MODEL = model.trim();

    // Write updated .env file
    writeEnvFile(envVars);

    // Update process.env for immediate use
    process.env.OLLAMA_URL = url.trim();
    process.env.OLLAMA_MODEL = model.trim();

    console.log('✅ Ollama settings saved successfully');

    res.json({
      success: true,
      message: 'Ollama settings saved successfully',
      configured: true
    });

  } catch (error) {
    console.error('Error saving Ollama settings:', error);
    res.status(500).json({
      error: 'Failed to save Ollama settings',
      message: error.message
    });
  }
});

module.exports = router;